//
// BatchResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BatchResponse: Codable {

    public enum Result: String, Codable { 
        case successful = "SUCCESSFUL"
        case failed = "FAILED"
        case partiallySuccessful = "PARTIALLY_SUCCESSFUL"
    }
    public var items: [BatchResponseItems]?
    public var totalItems: Int?
    public var result: Result?

    public init(items: [BatchResponseItems]? = nil, totalItems: Int? = nil, result: Result? = nil) {
        self.items = items
        self.totalItems = totalItems
        self.result = result
    }

    public enum CodingKeys: String, CodingKey { 
        case items = "Items"
        case totalItems = "TotalItems"
        case result = "Result"
    }

}
