//
// Category.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Category: Codable {

    /** Country Id */
    public var categoryId: UUID?
    /** Country Name */
    public var categoryName: String?

    public init(categoryId: UUID? = nil, categoryName: String? = nil) {
        self.categoryId = categoryId
        self.categoryName = categoryName
    }

    public enum CodingKeys: String, CodingKey { 
        case categoryId = "CategoryId"
        case categoryName = "CategoryName"
    }

}
