//
// InventoryItemUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InventoryItemUpdateRequest: Codable {

    public var title: Any?
    public var SKU: Any?
    public var barcode: Any?
    public var purchasePrice: Any?
    public var retailPrice: Any?
    public var taxRate: Any?
    public var categoryId: Any?
    public var height: Any?
    public var width: Any?
    public var depth: Any?
    public var weight: Any?
    public var trackingType: Any?
    public var batchNumberScanRequired: Any?
    public var serialNumberScanRequired: Any?
    public var _id: UUID?

    public init(title: Any? = nil, SKU: Any? = nil, barcode: Any? = nil, purchasePrice: Any? = nil, retailPrice: Any? = nil, taxRate: Any? = nil, categoryId: Any? = nil, height: Any? = nil, width: Any? = nil, depth: Any? = nil, weight: Any? = nil, trackingType: Any? = nil, batchNumberScanRequired: Any? = nil, serialNumberScanRequired: Any? = nil, _id: UUID? = nil) {
        self.title = title
        self.SKU = SKU
        self.barcode = barcode
        self.purchasePrice = purchasePrice
        self.retailPrice = retailPrice
        self.taxRate = taxRate
        self.categoryId = categoryId
        self.height = height
        self.width = width
        self.depth = depth
        self.weight = weight
        self.trackingType = trackingType
        self.batchNumberScanRequired = batchNumberScanRequired
        self.serialNumberScanRequired = serialNumberScanRequired
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case title = "Title"
        case SKU
        case barcode = "Barcode"
        case purchasePrice = "PurchasePrice"
        case retailPrice = "RetailPrice"
        case taxRate = "TaxRate"
        case categoryId = "CategoryId"
        case height = "Height"
        case width = "Width"
        case depth = "Depth"
        case weight = "Weight"
        case trackingType = "TrackingType"
        case batchNumberScanRequired = "BatchNumberScanRequired"
        case serialNumberScanRequired = "SerialNumberScanRequired"
        case _id = "Id"
    }

}
