//
// Location.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Location: Codable, Hashable {

    /** Location ID */
    public var stockLocationId: UUID?
    /** Stock Location number */
    public var stockLocationNumber: Int?
    /** Stock Location name */
    public var locationName: String?
    /** True if location is a fulfilment center */
    public var isFulfillmentCenter: Bool?
    /** Location tag */
    public var locationTag: String?
    /** True if location is warehouse managed */
    public var isWarehouseManaged: Bool?

    public init(stockLocationId: UUID? = nil, stockLocationNumber: Int? = nil, locationName: String? = nil, isFulfillmentCenter: Bool? = nil, locationTag: String? = nil, isWarehouseManaged: Bool? = nil) {
        self.stockLocationId = stockLocationId
        self.stockLocationNumber = stockLocationNumber
        self.locationName = locationName
        self.isFulfillmentCenter = isFulfillmentCenter
        self.locationTag = locationTag
        self.isWarehouseManaged = isWarehouseManaged
    }

    public enum CodingKeys: String, CodingKey { 
        case stockLocationId = "StockLocationId"
        case stockLocationNumber = "StockLocationNumber"
        case locationName = "LocationName"
        case isFulfillmentCenter = "IsFulfillmentCenter"
        case locationTag = "LocationTag"
        case isWarehouseManaged = "IsWarehouseManaged"
    }

}
