//
// InlineResponse403.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse403: Codable {

    public enum ErrorCode: String, Codable { 
        case forbidden = "FORBIDDEN"
    }
    public var errorCode: ErrorCode?
    public var errorDescription: String?

    public init(errorCode: ErrorCode? = nil, errorDescription: String? = nil) {
        self.errorCode = errorCode
        self.errorDescription = errorDescription
    }


}
