//
// LocationsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class LocationsAPI {
    
    private var headers: [String : String]
    
    init(token: String)
    {
        self.headers = [String:String]()
        self.headers["Authorization"] = token
    }
    
    /**
     Get Stock Locations

     - parameter completion: completion handler to receive the data and the error objects
     */
    open func locationsGet(completion: @escaping ((_ data: [Location]?,_ error: Error?) -> Void)) {
        locationsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Stock Locations
     - GET /locations

     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example=[ {
  "LocationTag" : "LocationTag",
  "StockLocationId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "StockLocationNumber" : 0,
  "IsWarehouseManaged" : true,
  "LocationName" : "LocationName",
  "IsFulfillmentCenter" : true
}, {
  "LocationTag" : "LocationTag",
  "StockLocationId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "StockLocationNumber" : 0,
  "IsWarehouseManaged" : true,
  "LocationName" : "LocationName",
  "IsFulfillmentCenter" : true
} ]}]

     - returns: RequestBuilder<[Location]> 
     */
    open func locationsGetWithRequestBuilder() -> RequestBuilder<[Location]> {
        let path = "/locations"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[Location]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()
        
        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: self.headers)
    }
}
